name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=momina-sheikh-dev&show_icons=true&theme=dracula&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"

      - name: Update README
        run: |
          sed -i 's|!\[GitHub Stats\](.*)|![GitHub Stats](stats.svg)|' README.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated GitHub Stats" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/momina-sheikh-dev/momina-sheikh-dev.git HEAD:main
